image: maven:3.9.6-eclipse-temurin-21-alpine

default:
  tags:
    - shared-fi

stages:
  - build
  - unit-test
  - integration-test

build:
  stage: build

  script:
    - echo "Building the project..."
    - mvn clean install -DskipTests --no-transfer-progress
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 month

unit-test:
  stage: unit-test

  script:
    - echo "Running unit tests..."
    - mvn test --no-transfer-progress
    - cat target/surefire-reports/*.txt
  dependencies:
    - build
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 month

integration-test:
  stage: integration-test
  script:
    - echo "Running integration tests..."
    - mvn verify --no-transfer-progress
    - cat target/failsafe-reports/*.txt
  dependencies:
    - build
  artifacts:
    when: always
    reports:
      junit: target/failsafe-reports/*.xml
    paths:
      - target/failsafe-reports/
    expire_in: 1 month
