version: '3.8'

services:
  builder:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    working_dir: /app
    command: mvn clean package -DskipTests

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    depends_on:
      - builder
    ports:
      - "8084:8084"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on:
      - builder
      - artemis
    ports:
      - "8091:8091"
    environment:
      - ARTEMIS_BROKER_URL=tcp://artemis:61616

  band-service:
    build:
      context: .
      dockerfile: band-service/Dockerfile
    depends_on:
      - builder
      - artemis
    ports:
      - "8092:8092"
    environment:
      - ARTEMIS_BROKER_URL=tcp://artemis:61616

  music-catalog-service:
    build:
      context: .
      dockerfile: music-catalog-service/Dockerfile
    depends_on:
      - builder
      - artemis
    ports:
      - "8093:8093"

  tour-service:
    build:
      context: .
      dockerfile: tour-service/Dockerfile
    depends_on:
      - builder
      - artemis
    ports:
      - "8094:8094"

  artemis:
    image: apache/activemq-artemis:2.41.0-alpine
    container_name: artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "1883:1883"
    volumes:
      - artemis-data:/var/lib/artemis/data
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: "true"
      DISABLE_SECURITY: "true"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  artemis-data:
  maven-repo: