openapi: 3.0.1
info:
  title: PA165 - Music Band Manager
  description: PA165 Spring 2025 student project - Music Band Manager
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
tags:
  - name: ApiGateway
  - name: BandService
  - name: MusicCatalog
  - name: ServiceRegistry
  - name: TourService
  - name: UserService
components:
  schemas:
    BandDto:
      title: A musical band
      description: object representing a musical band, with its manager and members
      properties:
        id: {type: integer, description: band id}
        name: {type: string, description: name of the band, example: Rammstein}
        musicalStyle: {type: string, description: musical style played by the band, example: industrial metal }
        logo: {type: string, description: url of band logo, nullable: true }
        managerId: {type: integer, description: id of the band manager}
        members: {type: array, items: {type: integer}, description: array of member id's}

    BandOfferDto:
      title: Offer to join a band
      description: object containing info regarding an offer to join a band
      properties:
        id: {type: integer, description: id of band offer}
        bandId: {type: integer, description: id of offering band}
        invitedMusicianId: {type: integer, description: id of invited musician}
        offeringManagerId: {type: integer, description: id of offer manager}
        status: {type: string, description: status of the offer, enum: ["Pending", "Accepted", "Rejected"]}

paths:
  /api/bands:
    post:
      tags:
        - BandService
      summary: creates a new band
      operationId: createBand
      parameters:
        - {name: name, in: query, required: true, schema: {type: string}, description: "name of the new music band"}
        - {name: musicalStyle, in: query, required: true, schema: {type: string}, description: "musical style played by the new band"}
        - {name: managerId, in: query, required: true, schema: {type: integer}, description: "Id of the manager of the new band"}
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BandDto"
        "400":
          description: cannot create given band
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
    get:
      tags:
        - BandService
      summary: returns searched band
      operationId: getBand
      parameters:
        - {name: id, in: query, required: true, schema: {type: integer}, description: "Id of queried band"}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BandDto"
        "404":
          description: given band not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
  /api/bands/offers:
    post:
      tags:
        - BandService
      summary: publishes new offer to join band
      operationId: postBandOffer
      parameters:
        - {name: bandId, in: query, required: true, schema: {type: integer}, description: "Id of offered band"}
        - {name: invitedMusicianId, in: query, required: true, schema: {type: integer}, description: "Id of invited musician"}
        - {name: offeringManagerId, in: query, required: true, schema: {type: integer}, description: "Id of offering manager"}
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BandOfferDto"
        "400":
          description: cannot create given offer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
    get:
      tags:
        - BandService
      summary: gets required offer
      operationId: getBandOffer
      parameters:
        - {name: offerId, in: query, required: true, schema: {type: integer}, description: "Id of searched band offer"}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BandOfferDto"
        "404":
          description: Given band offer cannot be found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

