spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka