{
 "title": "Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "App start date",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(process_start_time_seconds{job=\"band-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "description": "Shows the uptime of the services",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "process_uptime_seconds >= bool 1",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{method=\"GET\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "stat",
   "description": "Displays the number of connected nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hikaricp_connections", "legendFormat": "{{job}}" }
   ]
  }
 ]
}